project_id = "wutfcyskvfkunmvrvafz"

[functions.paynow-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = true

[functions.match-driver]
verify_jwt = true

[functions.create-paynow-payment]
verify_jwt = true